name: Release

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '.github/workflows/release.yml'
      - '.releaserc.json'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set correct Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm install \
            @semantic-release/changelog@6.0.3 \
            @semantic-release/git@10.0.1 \
            conventional-changelog-conventionalcommits@9.1.0

      - name: Release
        uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
